"""pending_processing

Revision ID: 19b66c2ef720
Revises: e257381e7350
Create Date: 2026-08-04 18:32:54.787385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19b66c2ef720'
down_revision: Union[str, Sequence[str], None] = 'e257381e7350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_processing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('process_after', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    # NOTE: autogenerate also proposed `op.drop_table('spatial_ref_sys')` here —
    # that's a PostGIS system table in this shared local container, unrelated
    # to this app's schema. Intentionally not dropped.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_processing')
    # ### end Alembic commands ###
